Config = {}

Config.MaxDistance = 2.0

Config.objects = {
	ButtonToStandUp = 73, -- // Default: X -- // https://docs.fivem.net/game-references/controls/
	SitAnimation = {anim='PROP_HUMAN_SEAT_CHAIR_MP_PLAYER'},
	BedBackAnimation = {dict='anim@gangops@morgue@table@', anim='body_search'},
	BedStomachAnimation = {anim='WORLD_HUMAN_SUNBATHE'},
	BedSitAnimation = {anim='WORLD_HUMAN_PICNIC'},
	locations = {
		{object="Prop_Off_Chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="apa_mp_h_stn_chairarm_09", verticalOffsetX=0.0, verticalOffsetY=0.13, verticalOffsetZ=-0.4, direction=185.0, bed=false},
		{object="ba_prop_battle_club_chair_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.15, direction=185.0, bed=false},
		{object="ba_prop_int_edgy_stool", verticalOffsetX=0.1, verticalOffsetY=-0.13, verticalOffsetZ=-0.8, direction=185.0, bed=false},
		{object="bkr_prop_biker_campbed_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=0.0, bed=true},
		{object="bkr_prop_clubhouse_chair_03", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="bkr_prop_clubhouse_offchair_01a", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=0.0, direction=180.0, bed=false},
		{object="ex_prop_offchair_exec_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="ex_prop_offchair_exec_04", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="gabz_pillbox_diagnostics_bed_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.9, direction=0.0, bed=true},
		{object="gabz_pillbox_diagnostics_bed_03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.9, direction=0.0, bed=true},
		{object="hei_prop_hei_skid_chair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.1, direction=180.0, bed=false},
		{object="hei_prop_heist_off_chair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="hei_prop_yah_seat_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="hei_prop_yah_seat_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=178.0, bed=false},
		{object="hei_prop_yah_seat_03", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="lr_prop_clubstool_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.8, direction=180.0, bed=false},
		{object="miss_rub_couch_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="p_armchair_01_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="p_clb_officechair_s", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="p_dinechair_01_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="p_ilev_p_easychair_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="p_lev_sofa_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="p_res_sofa_l_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="p_soloffchair_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="p_v_med_p_sofa_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="p_yacht_chair_01_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="p_yacht_sofa_01_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_bar_stool_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.8, direction=180.0, bed=false},
		{object="prop_bench_01a", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_bench_01b", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_bench_01c", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_bench_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_bench_03", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_bench_04", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_bench_05", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_bench_06", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_bench_07", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_bench_08", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_bench_09", verticalOffsetX=-0.1, verticalOffsetY=-0.0, verticalOffsetZ=-0.3, direction=180.0, bed=false},
		{object="prop_bench_10", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_bench_11", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_chair_01a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="prop_chair_01b", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="prop_chair_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="prop_chair_03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="prop_chair_04a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="prop_chair_04b", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="prop_chair_05", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="prop_chair_06", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="prop_chair_07", verticalOffsetX=-0.065, verticalOffsetY=0.1, verticalOffsetZ=-0.55, direction=180.0, bed=false},
		{object="prop_chair_08", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.0, direction=180.0, bed=false},
		{object="prop_chair_09", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="prop_chair_10", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_chateau_chair_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.0, direction=168.0, bed=false},
		{object="prop_clown_chair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="prop_cs_office_chair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="prop_direct_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_direct_chair_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_fib_3b_bench", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_gc_chair02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_ld_bench01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_ld_farm_chair01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_ld_farm_couch01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_ld_farm_couch02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_off_chair_03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="prop_off_chair_04", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="prop_off_chair_04_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_off_chair_04b", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_off_chair_05", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.41, direction=168.0, bed=false},
		{object="prop_old_deck_chair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_old_wood_chair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_rock_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_roller_car_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_roller_car_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_rub_couch01", verticalOffsetX=-0.0, verticalOffsetY=0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_rub_couch03", verticalOffsetX=-0.1, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_rub_couch04", verticalOffsetX=-0.1, verticalOffsetY=0.0, verticalOffsetZ=-0.49, direction=180.0, bed=false},
		{object="prop_skid_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.1, direction=180.0, bed=false},
		{object="prop_skid_chair_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.1, direction=185.0, bed=false},
		{object="prop_skid_chair_03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.1, direction=185.0, bed=false},
		{object="prop_sol_chair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="prop_swiss_ball_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.49, direction=5.0, bed=false},
		{object="prop_table_01_chr_a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.0, direction=168.0, bed=false},
		{object="prop_table_01_chr_b", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.0, direction=260.0, bed=false},
		{object="prop_table_02_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="prop_table_03_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="prop_table_03b_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="prop_table_04_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="prop_table_05_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.47, direction=168.0, bed=false},
		{object="prop_table_06_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.48, direction=185.0, bed=false},
		{object="prop_table_08_chr", verticalOffsetX=0.0, verticalOffsetY=0.1, verticalOffsetZ=-0.3, direction=180.0, bed=false},
		{object="prop_torture_ch_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.1, direction=180.0, bed=false},
		{object="prop_ven_market_stool", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.25, direction=168.0, bed=false},
		{object="prop_wait_bench_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_waiting_seat_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="prop_yacht_seat_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_yacht_seat_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="prop_yacht_seat_03", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="v_club_barchair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="v_club_officechair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="v_club_stagechair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="v_club_vuarmchair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="v_corp_bk_chair3", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="v_corp_cd_chair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="v_corp_lazychair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="v_corp_offchair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="v_ilev_chair02_ped", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.0, direction=185.0, bed=false},
		{object="v_ilev_fh_dineeamesa", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="v_ilev_fh_kitchenstool", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="v_ilev_leath_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="v_ilev_m_dinechair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="v_ilev_m_sofa", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="v_ilev_p_easychair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="v_ilev_ph_bench", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="v_ilev_tort_stool", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="v_ind_ss_chair01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=185.0, bed=false},
		{object="v_ind_ss_chair2", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.0, direction=185.0, bed=false},
		{object="v_med_bed1", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=0.0, bed=true},
		{object="v_med_bed2", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=0.0, bed=true},
		{object="v_med_emptybed", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=0.0, bed=true},
		{object="v_med_fabricchair1", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="v_res_fa_chair01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=185.0, bed=false},
		{object="v_res_fa_chair02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="v_res_fh_dineeamesa", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="v_res_fh_dineeamesb", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="v_res_m_armchair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="v_res_tre_sofa_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="v_ret_chair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
		{object="v_ret_gc_chair01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=185.0, bed=false},
		{object="v_ret_gc_chair02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.0, direction=185.0, bed=false},
		{object="v_ret_gc_chair03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.15, direction=185.0, bed=false},
		{object="v_serv_ct_chair02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
		{object="v_tre_sofa_mess_a_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="v_tre_sofa_mess_b_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="v_tre_sofa_mess_c_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="vw_prop_casino_chair_01a", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="vw_prop_casino_chair_01a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.75, direction=5.0, bed=false},
		{object="vw_prop_casino_track_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="vw_prop_vw_offchair_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="apa_mp_h_din_chair_12", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		{object="bkr_prop_clubhouse_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=0.1, direction=180.0, bed=false},

		-- 🪑 Standard Chairs
        {object="prop_off_chair_03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
        {object="prop_off_chair_04", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
        {object="prop_off_chair_05", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.41, direction=168.0, bed=false},
        {object="prop_chair_01a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
        {object="prop_chair_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
        {object="prop_chair_04a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
        {object="prop_chair_05", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
        {object="prop_chair_06", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
        {object="prop_chair_09", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
        {object="v_corp_offchair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},

        -- 🛋️ Sofas & Couches
        {object="prop_rub_couch01", verticalOffsetX=-0.0, verticalOffsetY=0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_rub_couch03", verticalOffsetX=-0.1, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_rub_couch04", verticalOffsetX=-0.1, verticalOffsetY=0.0, verticalOffsetZ=-0.49, direction=180.0, bed=false},
        {object="v_ilev_m_sofa", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="p_lev_sofa_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="p_res_sofa_l_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="apa_mp_h_stn_sofacorn_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},

        -- 🪵 Benches
        {object="prop_bench_01a", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_bench_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_bench_03", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_bench_04", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_bench_05", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_wait_bench_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="v_ilev_ph_bench", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},

        -- 🪚 Stools & Bar Seating
        {object="prop_bar_stool_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.8, direction=180.0, bed=false},
        {object="prop_ven_market_stool", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.25, direction=168.0, bed=false},
        {object="v_ilev_fh_kitchenstool", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_bar_stool_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.8, direction=180.0, bed=false},
        {object="prop_diner_stool_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.8, direction=180.0, bed=false},
        {object="v_ilev_bk_stool", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.82, direction=180.0, bed=false},

        -- 🪨 Natural Surfaces
        {object="prop_rock_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_rock_chair_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_rock_4_big2", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.0, direction=0.0, bed=false},
        {object="prop_logpile_06b", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=0.0, bed=false},
        {object="prop_beach_fire", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=0.0, bed=false},

        -- 🧰 Crates & Industrial
        {object="prop_crate_11e", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=0.0, bed=false},
        {object="prop_crate_01a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=0.0, bed=false},
        {object="prop_pallet_02a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.2, direction=0.0, bed=false},
        {object="prop_toolchest_05", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.35, direction=0.0, bed=false},
        {object="prop_skip_08a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.8, direction=0.0, bed=false},

        -- 🏖️ Outdoor & Leisure
        {object="prop_ld_deckchair_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=0.0, bed=false},
        {object="prop_pool_lounger", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=0.0, bed=false},
        {object="prop_skid_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.1, direction=180.0, bed=false},
        {object="prop_skid_chair_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.1, direction=185.0, bed=false},
        {object="prop_beach_lounger_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.2, direction=0.0, bed=false},
        {object="prop_beach_volball01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=0.0, bed=false},

        -- 🪜 Steps & Low Walls
        {object="prop_step_01a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=180.0, bed=false},
        {object="prop_step_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=180.0, bed=false},
        {object="prop_conc_blocks01a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=0.0, bed=false},
        {object="prop_cons_ply01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.2, direction=0.0, bed=false},
        {object="prop_cons_ply02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.2, direction=0.0, bed=false},

        -- 🛏️ Beds & Medical
        {object="v_med_bed1", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=0.0, bed=true},
        {object="v_med_bed2", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=0.0, bed=true},
        {object="v_med_examchair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=180.0, bed=false},
        {object="v_med_cor_medstool", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.8, direction=180.0, bed=false},
        {object="prop_ld_med_bed_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.2, direction=0.0, bed=true},

        -- 🚗 Vehicle Seats
        {object="prop_car_seat", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=0.0, bed=false},
        {object="prop_roller_car_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_roller_car_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_jetski_seat_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=0.0, bed=false},
        {object="prop_tractor_seat", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=0.0, bed=false},

        -- 🧸 Unique Props
        {object="prop_swivel_armchair_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=0.0, bed=false},
        {object="prop_elecbox_10", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.35, direction=0.0, bed=false},
        {object="prop_ld_toilet_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=0.0, bed=false},
        {object="prop_wheelchair_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=0.0, bed=false},
        {object="prop_beanbag_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=0.0, bed=false},
        {object="prop_ld_ferris_wheel", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=0.0, bed=false},

        -- 🏫 Public Seating
        {object="prop_bus_stop_05", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_street_chair_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=180.0, bed=false},
        {object="prop_street_chair_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=180.0, bed=false},
        {object="prop_sub_chair_01a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=180.0, bed=false},
        {object="prop_waiting_seat_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},

        -- 🧱 Construction Props
        {object="prop_cementbags01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=0.0, bed=false},
        {object="prop_conc_sacks_02a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=0.0, bed=false},
        {object="prop_pipes_conc_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=0.0, bed=false},
        {object="prop_roadcone02b", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=0.0, bed=false},

        -- 🧪 Lab Equipment
        {object="v_ilev_lest_bigscreen", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.8, direction=180.0, bed=false},
        {object="v_ilev_lester_doorwin", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.7, direction=180.0, bed=false},
        {object="prop_ld_test_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.35, direction=0.0, bed=false},

        -- 🍽️ Restaurant Furniture
        {object="prop_table_01_chr_a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.0, direction=168.0, bed=false},
        {object="prop_table_02_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
        {object="prop_table_03_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
        {object="prop_table_04_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=185.0, bed=false},
        {object="prop_table_05_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.47, direction=168.0, bed=false},
        {object="v_ret_fh_chair01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},

        -- 🎮 Arcade & Gaming
        {object="vw_prop_casino_chair_01a", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="vw_prop_casino_track_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="vw_prop_vw_arcade_01_s", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=180.0, bed=false},
        {object="prop_arcade_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.8, direction=180.0, bed=false},

        -- 🧱 Concrete Structures
        {object="prop_conc_blocks01a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=0.0, bed=false},
        {object="prop_conc_blocks02a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=0.0, bed=false},
        {object="prop_conc_blocks03a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=0.0, bed=false},
        {object="prop_conc_pipes_01a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=0.0, bed=false},

        -- 🏞️ Park Furniture
        {object="prop_picnictable_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_picnictable_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_bench_11", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_bench_12", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_garden_chair_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=0.0, bed=false},

        -- 🏠 Interior Props
        {object="v_res_fh_sofa", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="v_res_m_h_sofa", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="v_res_tre_stool", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.8, direction=180.0, bed=false},
        {object="v_res_tre_sofa", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="v_res_d_highchair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.2, direction=0.0, bed=false},

        -- 🛋️ Additional Couches
        {object="p_v_med_p_sofa_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="apa_mp_h_yacht_sofa_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="apa_mp_h_yacht_sofa_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="bkr_prop_biker_couch_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="bkr_prop_biker_couch_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="bkr_prop_biker_couch_03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},

        -- 🪑 Specialty Chairs
        {object="prop_wheelchair_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=0.0, bed=false},
        {object="v_ilev_m_dinechair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
        {object="v_ilev_p_easychair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="v_med_fabricchair1", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=168.0, bed=false},
        {object="v_res_mbchair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="v_res_mp_stripchair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="v_ret_ta_stool", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.8, direction=180.0, bed=false},
        {object="prop_torture_ch_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.1, direction=180.0, bed=false},
        {object="prop_ld_farm_chair01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_ld_farm_couch01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},
        {object="prop_ld_farm_couch02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false},


	}
}